// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhFRDKHwBLf3oUTiJxQmMA2xYjbT5evU',
    appId: '1:932655762618:web:556c2398ccd63f9e668683',
    messagingSenderId: '932655762618',
    projectId: 'homepulse-ac95f',
    authDomain: 'homepulse-ac95f.firebaseapp.com',
    storageBucket: 'homepulse-ac95f.firebasestorage.app',
    measurementId: 'G-KBK0VD80D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVEM6iwigArN-ezm7OhpMxAptyliaUsaE',
    appId: '1:932655762618:android:fad18373fb5b4966668683',
    messagingSenderId: '932655762618',
    projectId: 'homepulse-ac95f',
    storageBucket: 'homepulse-ac95f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrW8tf0TRXb6Ocj6UfOtkb1L2LqGDcdf4',
    appId: '1:932655762618:ios:ea14c660858f0b13668683',
    messagingSenderId: '932655762618',
    projectId: 'homepulse-ac95f',
    storageBucket: 'homepulse-ac95f.firebasestorage.app',
    iosBundleId: 'com.example.homePulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrW8tf0TRXb6Ocj6UfOtkb1L2LqGDcdf4',
    appId: '1:932655762618:ios:ea14c660858f0b13668683',
    messagingSenderId: '932655762618',
    projectId: 'homepulse-ac95f',
    storageBucket: 'homepulse-ac95f.firebasestorage.app',
    iosBundleId: 'com.example.homePulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZhFRDKHwBLf3oUTiJxQmMA2xYjbT5evU',
    appId: '1:932655762618:web:b9098894fc0c0aad668683',
    messagingSenderId: '932655762618',
    projectId: 'homepulse-ac95f',
    authDomain: 'homepulse-ac95f.firebaseapp.com',
    storageBucket: 'homepulse-ac95f.firebasestorage.app',
    measurementId: 'G-013M39NHNX',
  );
}
